// <auto-generated />
using System;
using Du_An_Dua_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Du_An_Dua_MVC.Migrations
{
    [DbContext(typeof(DuAnDuaDbContext))]
    [Migration("20260121132345_TaoBangGiaoDich_v1")]
    partial class TaoBangGiaoDich_v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Du_An_Dua_MVC.Models.DoiTac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LoaiDoiTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDoiTac")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DoiTac", (string)null);
                });

            modelBuilder.Entity("Du_An_Dua_MVC.Models.GiaoDich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoiTacId")
                        .HasColumnType("int");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMuaHang")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiDuaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGiaoDich")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DoiTacId");

                    b.HasIndex("LoaiDuaId");

                    b.ToTable("GiaoDichs");
                });

            modelBuilder.Entity("Du_An_Dua_MVC.Models.LoaiDua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("GiaThamKhao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiDua", (string)null);
                });

            modelBuilder.Entity("Du_An_Dua_MVC.Models.GiaoDich", b =>
                {
                    b.HasOne("Du_An_Dua_MVC.Models.DoiTac", "DoiTac")
                        .WithMany()
                        .HasForeignKey("DoiTacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Du_An_Dua_MVC.Models.LoaiDua", "LoaiDua")
                        .WithMany()
                        .HasForeignKey("LoaiDuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoiTac");

                    b.Navigation("LoaiDua");
                });
#pragma warning restore 612, 618
        }
    }
}
