// <auto-generated /> 
// 👆 Dòng này báo hiệu: "Đây là code do máy tạo, con người đừng táy máy vào"

using System;
using Du_An_Dua_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Du_An_Dua_MVC.Migrations
{
    [DbContext(typeof(DuAnDuaDbContext))]
    partial class DuAnDuaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            // Cấu hình chung cho SQL Server
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // ======================================================
            // 1. BẢNG ĐỐI TÁC (Đã được chụp lại đầy đủ)
            // ======================================================
            modelBuilder.Entity("Du_An_Dua_MVC.Models.DoiTac", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd() // Tự tăng
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("LoaiDoiTac")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("SoDienThoai")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("TenDoiTac")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id"); // Khóa chính

                b.ToTable("DoiTac", (string)null); // Tên bảng trong SQL
            });

            // ======================================================
            // 2. BẢNG GIAO DỊCH (Trái tim của hệ thống)
            // ======================================================
            modelBuilder.Entity("Du_An_Dua_MVC.Models.GiaoDich", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                // Các cột dữ liệu
                b.Property<int>("DoiTacId").HasColumnType("int");
                b.Property<double>("DonGia").HasColumnType("float");
                b.Property<string>("GhiChu").HasColumnType("nvarchar(max)");
                b.Property<bool>("IsMuaHang").HasColumnType("bit");
                b.Property<int>("LoaiDuaId").HasColumnType("int");
                b.Property<DateTime>("NgayGiaoDich").HasColumnType("datetime2");
                b.Property<int>("SoLuong").HasColumnType("int");
                b.Property<double>("ThanhTien").HasColumnType("float");

                b.HasKey("Id");

                // Mục lục tìm kiếm nhanh (Index)
                b.HasIndex("DoiTacId");
                b.HasIndex("LoaiDuaId");

                b.ToTable("GiaoDichs"); // Lưu ý: Bảng này đang tên là số nhiều "s"
            });

            // ======================================================
            // 3. BẢNG LOẠI DỪA (Cập nhật mới nhất có Tồn Kho)
            // ======================================================
            modelBuilder.Entity("Du_An_Dua_MVC.Models.LoaiDua", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<decimal>("GiaThamKhao")
                    .HasColumnType("decimal(18,2)");

                // 👇 CỘT MỚI THÊM ĐÂY RỒI! 
                // Nhờ file Snapshot này mà hệ thống biết bảng Dừa đã có cột Tồn Kho.
                b.Property<int>("SoLuongTon")
                    .HasColumnType("int");

                b.Property<string>("TenLoai")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("LoaiDua", (string)null);
            });

            // ======================================================
            // 4. BẢNG USER (Bảo vệ)
            // ======================================================
            modelBuilder.Entity("Du_An_Dua_MVC.Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("FullName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Password").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Role").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Username").IsRequired().HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("User", (string)null);
            });

            // ======================================================
            // 5. CÁC MỐI QUAN HỆ (Sợi dây kết nối)
            // ======================================================
            modelBuilder.Entity("Du_An_Dua_MVC.Models.GiaoDich", b =>
            {
                // Giao dịch này thuộc về Đối Tác nào?
                b.HasOne("Du_An_Dua_MVC.Models.DoiTac", "DoiTac")
                    .WithMany()
                    .HasForeignKey("DoiTacId")
                    .OnDelete(DeleteBehavior.Cascade) // Xóa cha mất con
                    .IsRequired();

                // Giao dịch này mua bán Loại Dừa nào?
                b.HasOne("Du_An_Dua_MVC.Models.LoaiDua", "LoaiDua")
                    .WithMany()
                    .HasForeignKey("LoaiDuaId")
                    .OnDelete(DeleteBehavior.Cascade) // Xóa cha mất con
                    .IsRequired();

                // Các dòng này giúp code C# hiểu để dùng lệnh .Include()
                b.Navigation("DoiTac");
                b.Navigation("LoaiDua");
            });
#pragma warning restore 612, 618
        }
    }
}